<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LLI844K" failures="1" tests="9" name="testCases.LoginPageValidatation" time="56.839" errors="0" timestamp="2025-05-11T23:52:45 IST" skipped="3">
  <testcase classname="testCases.LoginPageValidatation" name="validate_email_address" time="6.593"/>
  <testcase classname="testCases.LoginPageValidatation" name="validate_register_link" time="7.476"/>
  <testcase classname="testCases.LoginPageValidatation" name="validate_register_button" time="6.549"/>
  <testcase classname="testCases.LoginPageValidatation" name="validate_login_text" time="6.945"/>
  <testcase classname="testCases.LoginPageValidatation" name="validate_title" time="6.965">
    <skipped/>
  </testcase> <!-- validate_title -->
  <testcase classname="testCases.LoginPageValidatation" name="validate_forgot_password_link" time="6.638"/>
  <testcase classname="testCases.LoginPageValidatation" name="validate_title" time="8.657">
    <skipped/>
  </testcase> <!-- validate_title -->
  <testcase classname="testCases.LoginPageValidatation" name="validate_title" time="7.016">
    <failure message="expected [Let&#039;s Sh] but found [Let&#039;s Shop]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Let's Sh] but found [Let's Shop]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.LoginPageValidatation.validate_title(LoginPageValidatation.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- validate_title -->
  <testcase classname="testCases.LoginPageValidatation" name="login_page_validations">
    <skipped/>
  </testcase> <!-- login_page_validations -->
</testsuite> <!-- testCases.LoginPageValidatation -->
